apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "tst-mobil-micro"
generatorOptions:
  disableNameSuffixHash: true
commonAnnotations:
  app.kubernetes.io/managed-by: kustomize
resources:
  - deployment.yaml
  - service.yaml