apiVersion: v1
data:
  accounts.password: MTIzNDU3
kind: Secret
metadata:
  creationTimestamp: "2021-03-12T14:45:32Z"
  name: account-secret
  namespace: tst-micro
  resourceVersion: "109887507"
  selfLink: /api/v1/namespaces/tst-micro/secrets/account-secret
  uid: 20bd31b4-6dac-423c-bc76-5aa263c7ab3b
type: Opaque
