apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: tst-micro
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: null
  selector:
    app: account-service