apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-service
  namespace: tst-micro
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: credit-service
  template:
    metadata:
      labels:
        app: credit-service
    spec:
      containers:
        - name: credit-service
          image: sdlc.yapikredi.com.tr/internal-docker-app/com/ykb/digital/mobile/credit/credit:latest-dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 10
            failureThreshold: 90
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
            periodSeconds: 60
      imagePullSecrets:
        - name: registrypullsecret